### ISSUE TITLE
Mission did not work

### ISSUE THREAD

**Issue by sancron** [whiztler/Wolfpack#9]
After try to play your Missions with 1.54 plus CBA 2.2.0, ACE3 3.4.1 and TFAR 0.9.8 the Missions end up with "Mission Failed" in cause that all people died, but we wasn't able to play a minute.

**Comment by whiztler** [comment]
Which mission (day) was this? Did you edit the mission?
If you have a RPT, please upload at pastebin.com

**Comment by sancron** [comment]
I was Test Mission Day 1 and 2 and i was use the Mission without any editing by me. Direct Upload from your Zip as PBO. And here ist the RPT Log: http://hastebin.com/imevidimos.tex

Just autoInit the WarmUp Mission, then i was use #missions to load the Day 1. After Role Selecting and  loading, the first thing i was see are "Mission Failed" in cause all players dead.

Edit: I see that the RPT says:
"ADF RPT: Init - Number of clients connected: 0"

But that should be wrong.

**Comment by whiztler** [comment]
Thanks for the RPT.

I cannot spot any errors. The mission is executed correctly and runs correctly. The fact that is does not detect any players means that the issue is with the server. It is not the mission detecting any players, it is the server not detecting players. The reporting is server based.

There are currently several communities currently playing Wolfpack missions without problems.

Have a look at your server settings to see if there's anything wrong.

**Comment by sancron** [comment]
Ok here are the Setup of my Server as Base i use the Dedicated Server Pack:

Arma 3 Version: 1.54.133596

Startup Parameter:
-ip=89.163.144.208 -port=2302 -name=Panzerbrigade21 -profiles=config -cfg=config\a3basic.cfg -config=config\a3server.cfg -par=config\a3parameter.cfg -enableHT -exThreads=1

a3server.cfg:
http://hastebin.com/acipufazef.avrasm

a3parameter.cfg
http://hastebin.com/vocimujade.mel

a3basic.cfg
http://hastebin.com/ujefelegaj.avrasm

Used Mods:
CBA_A3 - 2.2.0.151130
ACE3 - 3.4.1
TFAR - 0.9.8

beserver.cfg is empty for now. If you need other Informations i will provide it.

**Comment by whiztler** [comment]
I am by no means a server specialist. What I could spot:

Server.cfg
Last entry of missionWhitelist[] remove the comma (,)
You have verifysignatures set at 2 (strict(. Have you installed als the BI keys for the mods? Can you logon your server as player without mod errors?

Rest looks all okay. I presume server is same version as your ARMA client (1.54).

Have you tried any other MP missions?

**Comment by sancron** [comment]
No Problems, and i have no Problem to Play the Warm-Up Mission form you and other Missions only when i try to load Day 1, Day 2 or Vol. 2 i got instead Mission Failed with All Died

**Comment by whiztler** [comment]
Have you tried any other (no Wolfpack) multiplayer missions with your modline?

**Comment by sancron** [comment]
Yes our Community Zeus MilSim Mission runs fine, crCTI Kastenbier Edition runs no Problems at all. That was the reaseon why i conntact you.

**Comment by whiztler** [comment]
Strange. Dunno what to tell you. Like I mentioned, several clans currently playing Wolfpack. Same version as you have. 

Only thing I can think off is that it could be a mod issue. Try running with only CBA enabled on both the server and the client.
If that works than add 1 mod and re-test till you find which mod causes the problem.

**Comment by sancron** [comment]
This i was already test. Only enabled CBA and the same thing happens, are you shure that other communitys don't edit the Mission maybe a little bit?

**Comment by whiztler** [comment]
Not sure buddy. But I am currently testing a new version. Release sometime next week. Hopefully it will solve your problems.

**Comment by whiztler** [comment]
Version 1.63 is out. We have tested all missions on a dedicated server (with and without HC).

Please report back if you still have issues.

**Comment by sancron** [comment]
Hello, no Errors at all, i found out what happend. I can reproduce the Error now on 1.62 and 1.63 but i also know how to fix it now. It's not a fault directly by your Mission, it's the way the Dedicated Server useses the Startup-Parameter "-autoInit" if you start your Server with this Parameter, you got this error. But thanks for your Repley and your great work.

**Comment by whiztler** [comment]
Great to hear buddy!
